### PR TITLE
add support for new apple m1 processor - implemented as a fallback - …

### PR DESCRIPTION
**Pull request by sakes**
…source of bug: lib bin-wrapper is unable to identify arch for new apple m1

### CODE REVIEW

**Comment by sakes** [comment]
@XhmikosR, here is the pr as requested.  I executed `npm test` on my M1 and it passed.

https://github.com/fenneclab/hugo-bin/issues/118

**Comment by XhmikosR** [comment]
This breaks things for other macOS arches as you can see by the tests...

**Comment by sakes** [comment]
Strange, worked locally.  Well, in order to find a fix (too bad not working) I had to dig into bin-wrapper's code, fix a bunch of lint errors to get the tests to run, and then confirmed it was returning undefined for my arch.

I would have attempted to fix the issue in bin-wrapper, but it appears it was abandoned 3 years ago, so i attempted to solve here.

Sadly, i through away my changes for bin-wrapper, and am out of time this weekend.

I'll try to give it another go next weekend.

**Comment by sakes** [comment]
Declining as some CI tests failed.

**Pull request closed without merging**
