### PR TITLE
Update devDependencies and drop Node.js < 8 support.

### PR DESCRIPTION
**Pull request by XhmikosR**
Draft until Hugo 0.58.0 is out.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@satoshun00 I haven't heard from you. Do you agree with this? Hugo 0.58.0 is out and I'd like to release a new version. Otherwise I'll drop this in the next Hugo minor release.

**Comment by satoshun00** [comment]
Sorry for late reply.
I agree with dropping Node.js < 8 support.

**Comment by XhmikosR** [comment]
Alright, let's merge this in the next Hugo minor release. I might need to update the branch by that time again.

**Comment by XhmikosR** [comment]
After thinking more about it, we should bump the major version if we want to follow semver properly.

I'll leave this unmerged for the time being.

**Pull request closed without merging**
