### PR TITLE
Switch to rimraf for deleting the folder.

### PR DESCRIPTION
**Pull request by XhmikosR**
@satoshun00: I don't like that you squashed my previous patch. I'd like to fix it but it'll need force pushing the master branch...

Anyway, here's another small patch. Makes the dependency tree smaller.

### CODE REVIEW

**Comment by satoshun00** [comment]
LGTM

**Comment by satoshun00** [comment]
@XhmikosR 

Can I merge these PRs? (Everything looks good to me)

- https://github.com/fenneclab/hugo-bin/pull/70
- https://github.com/fenneclab/hugo-bin/pull/71
- https://github.com/fenneclab/hugo-bin/pull/72

**Comment by XhmikosR** [comment]
Yes, you can. Just don't squash my PRs please. I always take care of that manually if needed :)

I also have one more patch to submit after these PRs.

**Comment by XhmikosR** [comment]
@satoshun00: you can safely use a rebase instead of a merge commit in the future.

**Pull request merged**
