### PR TITLE
Switch to GitHub Actions CI.

### PR DESCRIPTION
**Pull request by XhmikosR**
This needs the publish step. Any help is welcome.

After this is merged Travis should be removed from integrations and hooks.

EDIT: This reminds me, the master branch should be protected @satoshun00. And while at it enable the option for the branches to be up to date and also delete `HEAD` branches.

EDIT2: Also please make sure you have 2fa enabled on GitHub and on npm.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I haven't made any progress with publishing mostly because we need to filter the events. Any help is welcome.

**Comment by XhmikosR** [comment]
@satoshun00 can you check https://github.com/fenneclab/hugo-bin/pull/103#issue-310971254?

Note that this is untested. This will need `NPM_AUTH_TOKEN` added in repo secrets.

What I'm not sure how to achieve is make sure tests succeed before publishing.

**Comment by XhmikosR** [comment]
@satoshun00 I really think we should move with this; Travis CI is so much slower.

**Comment by XhmikosR** [comment]
@satoshun00 ping. This is really important to get it to work ASAP. Please don't make me fork this project :)

**Comment by XhmikosR** [comment]
@satoshun00 I'm going to have to fork the repo and stop my involvement here unless we manage to move to GitHub Actions.

**Comment by XhmikosR** [comment]
@satoshun00 I hate to do this but yet another ping. I see you are active on GitHub. I need npm push rights or admin rights for the repo here. I don't like forking projects...

**Comment by satoshun00** [comment]
@XhmikosR 
I'm sorry for late reply.
I have set `NPM_TOKEN` secret to this repository.
Can you merge and test it?

**Comment by XhmikosR** [comment]
@satoshun00 I'll merge it and I'll cut a new patch version to test it.

**Comment by satoshun00** [comment]
Thank you  so much!
I have checked publish is ok.

**Comment by XhmikosR** [comment]
@satoshun00 NP. I'd still like to have npm publish rights and admin rights to this repo to make sure this doesn't happen again in the future.

**Comment by satoshun00** [comment]
@XhmikosR 
OK. I'll do that then please tell me your npmjs.com username.

**Comment by XhmikosR** [comment]
It's the same one as here but lowercase `xhmikosr` https://www.npmjs.com/~xhmikosr

**Comment by satoshun00** [comment]
I have invited you to hugo-bin package.

**Comment by XhmikosR** [comment]
@satoshun00 I don't seem to have admin rights on npm. Or this repo. It's the only way we prevent future issues...

**Comment by satoshun00** [comment]
I have now done the following:
```
$ npm owner add xhmikosr hugo-bin
+ xhmikosr (hugo-bin)
```

**Comment by XhmikosR** [comment]
OK, now I do have admin rights on the npm registry. I still don't have admin rights for this repo, though.

Does the `fenneclab` user need to have push rights on npm?

**Comment by satoshun00** [comment]
I have changed your role to Admin on this repo.

> Does the fenneclab user need to have push rights on npm?

Yes. I use this account as bot user.

**Comment by XhmikosR** [comment]
@satoshun00 let's reduce the accounts that have publish rights and definitely enforce 2FA for publishing so that we are safer. After that, please change the `NPM_TOKEN` to an automation one.

**Comment by XhmikosR** [comment]
@satoshun00 ping ^^

**Pull request merged**
